nhnacademy-be4-ckin/ckin-front

- src/main/java/store/ckin/front/advice/WebControllerAdvice.java
- src/main/java/store/ckin/front/config/SecurityConfig.java
- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/member/filter/CustomLoginFilter.java
- src/main/java/store/ckin/front/member/filter/JwtFilter.java
- src/main/java/store/ckin/front/member/service/MemberDetailsService.java
- src/main/java/store/ckin/front/member/service/MemberService.java
- src/main/java/store/ckin/front/member/service/impl/MemberServiceImpl.java
- src/main/java/store/ckin/front/token/adapter/impl/TokenAdapterImpl.java
- src/main/java/store/ckin/front/util/CookieUtil.java
> [REFACTOR] 오류 수정

- src/main/java/store/ckin/front/exception/CookieNotFoundException.java
- src/main/java/store/ckin/front/member/filter/JwtFilter.java
- src/main/java/store/ckin/front/util/CookieUtil.java
- src/main/resources/templates/admin/tag/index.html
- src/main/resources/templates/fragments/admin-sidebar.html
#88 
위 오류 해결 및 태그 관리 -> 관리자 페이지에 추가 및 연동
> [FIX, FEAT] 쿠키 NullPointerException 오류 해결 및 태그 관리 관리자 페이지에 추가

- src/main/java/store/ckin/front/member/filter/JwtFilter.java
> [FIX] JwtFilter Conflict 해결

- src/main/java/store/ckin/front/member/adapter/MemberAdapter.java
- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/member/controller/MemberController.java
- src/main/java/store/ckin/front/member/domain/response/MemberMyPageResponseDto.java
- src/main/java/store/ckin/front/member/filter/JwtFilter.java
- src/main/java/store/ckin/front/member/service/MemberService.java
- src/main/java/store/ckin/front/member/service/impl/MemberServiceImpl.java
- src/main/java/store/ckin/front/util/JwtUtil.java
- src/main/resources/static/css/mypageStyle.css
- src/main/resources/templates/fragments/admin-nav.html
- src/main/resources/templates/fragments/index-header.html
- src/main/resources/templates/fragments/mypage-sidebar.html
- src/main/resources/templates/layouts/mypage-default.html
- src/main/resources/templates/member/mypage.html
> [FEAT] 마이 페이지 View

- src/main/java/store/ckin/front/author/controller/AuthorController.java
- src/main/java/store/ckin/front/author/dto/request/AuthorCreateRequestDto.java
- src/main/resources/templates/admin/author/index.html
- src/main/resources/templates/fragments/admin-sidebar.html
> [DESIGN] 관리자 페이지 저자 사이드 바 추가

- pom.xml
- src/main/java/store/ckin/front/config/properties/TossProperties.java
- src/main/java/store/ckin/front/payment/controller/PaymentController.java
- src/main/java/store/ckin/front/payment/controller/PaymentRestController.java
- src/main/java/store/ckin/front/sale/controller/SaleController.java
- src/main/java/store/ckin/front/sale/dto/request/SaleCreateRequestDto.java
- src/main/java/store/ckin/front/sale/dto/response/SaleWithBookResponseDto.java
- src/main/resources/application.properties
- src/main/resources/static/css/toss.css
- src/main/resources/static/js/sale/payment.js
- src/main/resources/static/js/toss.js
- src/main/resources/templates/payment/checkout.html
- src/main/resources/templates/payment/fail.html
- src/main/resources/templates/payment/success.html
- src/main/resources/templates/sale/main.html
- src/main/resources/templates/sale/success.html
#93 
> 요청된 주문에 대한 상세 정보
> ![image](https://github.com/nhnacademy-be4-ckin/ckin-front/assets/84575041/e4f8753b-669d-44a4-8fe8-df2c3c86430a)
- 결제에 관한 정보를 JSON으로 받을 수 있습니다.
- 결제를 실패할 경우 에러 코드와 주문 번호를 같이 넘겨주게 됩니다.
현재 결제하기 요청 URL은
`GET /payment/{saleId}` 와 같은 방식을 통해 결제를 진행할 주문의 상세 정보를 가져오게 됩니다.
이렇게 saleId를 회원에게 노출해도 상관이 없을까요?
만약, 노출이 되지 않게 하려면 `결제하기` 버튼을 `POST` 방식으로 결제 페이지를 요청해야되는데 이렇게 하는게 맞을까요?
> [FEAT] 토스페이먼츠 API 연동

- src/main/java/store/ckin/front/book/adapter/impl/BookAdapterImpl.java
> [FIX] file 관련 SonarQube 오류 수정

- src/main/java/store/ckin/front/book/dto/response/BookExtractionResponseDto.java
- src/main/java/store/ckin/front/book/service/BookService.java
- src/main/java/store/ckin/front/payment/adpter/PaymentAdapter.java
- src/main/java/store/ckin/front/payment/adpter/impl/PaymentAdapterImpl.java
- src/main/java/store/ckin/front/payment/controller/PaymentController.java
- src/main/java/store/ckin/front/payment/facde/PaymentFacade.java
- src/main/java/store/ckin/front/payment/service/PaymentService.java
- src/main/java/store/ckin/front/payment/service/impl/PaymentServiceImpl.java
- src/main/java/store/ckin/front/sale/adapter/SaleAdapter.java
- src/main/java/store/ckin/front/sale/adapter/impl/SaleAdapterImpl.java
- src/main/java/store/ckin/front/sale/controller/SaleController.java
- src/main/java/store/ckin/front/sale/dto/response/SaleInfoResponseDto.java
- src/main/java/store/ckin/front/sale/service/SaleService.java
- src/main/java/store/ckin/front/sale/service/impl/SaleServiceImpl.java
- src/main/resources/templates/sale/main.html
- src/main/resources/templates/sale/success.html
DB에 저장된 File URL을 가져와 해당 URL을 보여주는 방식으로 변경하였습니다.
> [FEAT] 주문 - 썸네일 파일 불러오기

- src/main/java/store/ckin/front/cart/controller/CartController.java
- src/main/java/store/ckin/front/cart/dto/domain/CartItem.java
- src/main/java/store/ckin/front/cart/dto/request/CartItemCreateRequestDto.java
- src/main/java/store/ckin/front/cart/exception/ItemAlreadyExistException.java
- src/main/java/store/ckin/front/cart/service/CartService.java
- src/main/java/store/ckin/front/cart/service/impl/CartServiceImpl.java
- src/main/resources/static/css/adminStyle.css
- src/main/resources/static/css/main.css
- src/main/resources/static/css/navigation.css
- src/main/resources/templates/cart/index.html
- src/main/resources/templates/product/view.html
> [FEAT] 상품 상세-장바구니 추가 구현, 썸네일 이미지 및 정상가 표시

- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
2024년 3월 11일 배포 - 배포 환경 Redis 데이터베이스 지정
> [DEPLOY] 레디스 수정 

- src/main/java/store/ckin/front/book/controller/BookRestController.java
- src/main/resources/templates/admin/book/create.html
- src/main/resources/templates/admin/book/update.html
> 
> 잘못된 엔드포인트 때문에 생성요청 안되던 것 수정했습니다.
>
> [FIX] 책 생성 엔드포인트 수정

- src/main/java/store/ckin/front/cart/interceptor/CartIdInitInterceptor.java
> [REFACTOR] 장바구니 쿠키 Path 지정

- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/util/JwtUtil.java
- src/main/resources/templates/member/mypage.html
- 마이페이지가 안들어가지는 에러 수정
- 토큰 만료 여부 확인 메서드 에러 수정
>
> [FIX] 배포환경 에러 수정

- src/main/java/store/ckin/front/cart/controller/CartController.java
- src/main/java/store/ckin/front/sale/controller/SaleController.java
- src/main/java/store/ckin/front/sale/facade/SaleFacade.java
> [DEPLOY] 에러 수정

- src/main/resources/templates/sale/main.html
> [DEPLOY] 주문 타임리프 수정 후 배포

- src/main/java/store/ckin/front/member/controller/MemberController.java
- src/main/resources/templates/fragments/mypage-sidebar.html
> [FIX] 마이페이지 버그 확인용 로그

- src/main/resources/templates/sale/main.html
> [DEPLOY] 에러 테스트

- src/main/java/store/ckin/front/member/service/impl/MemberServiceImpl.java
> [FIX] 마이페이지 배포환경 테스트

- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/member/service/impl/MemberServiceImpl.java
> [FIX] 마이페이지 로그 확인

- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/member/service/impl/MemberServiceImpl.java
> [DEPLOY] 마이페이지 버그 수정 2

- src/main/java/store/ckin/front/cart/controller/CartController.java
- src/main/java/store/ckin/front/sale/adapter/SaleAdapter.java
- src/main/java/store/ckin/front/sale/adapter/impl/SaleAdapterImpl.java
- src/main/java/store/ckin/front/sale/controller/SaleController.java
- src/main/java/store/ckin/front/sale/facade/SaleFacade.java
- src/main/java/store/ckin/front/sale/service/SaleService.java
- src/main/java/store/ckin/front/sale/service/impl/SaleServiceImpl.java
- 장바구니 -> 주문 폼 (CART_ID)
- 주문 폼 -> 주문 성공 페이지 (SALE_ID)
위의 두 방식 모두 RedirectAttributes의 addFlashAttribute를 사용하는 방식을 수정하였습니다.
> [FEAT] 주문 - RedirectAttributes 수정

- src/main/java/store/ckin/front/sale/controller/AdminSaleController.java
- src/main/resources/templates/admin/sale/main.html
> [DEPLOY] 주문 전체 조회 페이징 수정

- src/main/resources/templates/admin/book/create.html
- src/main/resources/templates/admin/book/update.html
> 등록, 수정 시 카테고리 작가 설정 안되면 버튼 비활성화
> [REFACTOR] 등록, 수정 시 카테고리 작가 설정 안되면 버튼 비활성화

- src/main/java/store/ckin/front/author/controller/AuthorController.java
> [FIX] 작가 검색 path 수정

- src/main/resources/application.properties
> [REFACTOR] 파일 크기가 큰 파일 요청 보내지게 수정

- src/main/java/store/ckin/front/member/filter/CustomLoginFilter.java
- src/main/java/store/ckin/front/oauth/CustomOAuth2UserRequestConverter.java
- src/main/java/store/ckin/front/oauth/CustomOAuth2UserService.java
- src/main/resources/application-prod.properties
- src/main/resources/static/css/login.css
- src/main/resources/static/js/login.js
- src/main/resources/templates/layouts/mypage-default.html
- src/main/resources/templates/member/login.html
- 배포용 페이코 로그인 어플리케이션을 따로 만들어 설정하였습니다.
- 로그인 View 에 CSS, JS 적용하였습니다.
- 마이페이지 header layout을 추가하였습니다.
>
> [REFACTOR] 로그인 View & PAYCO 로그인

- src/main/java/store/ckin/front/config/SecurityConfig.java
- src/main/java/store/ckin/front/oauth/HttpCookieOAuth2AuthorizationRequestRepository.java
- src/main/java/store/ckin/front/util/CookieUtil.java
> [FEAT] HttpCookieOAuth2AuthorizationRequestRepository

- src/main/java/store/ckin/front/config/SecurityConfig.java
- src/main/java/store/ckin/front/oauth/HttpCookieOAuth2AuthorizationRequestRepository.java
- src/main/java/store/ckin/front/product/controller/ProductController.java
- src/main/java/store/ckin/front/util/CookieUtil.java
> [DEPLOY] 페이코 로그인 오류 수정

- src/main/java/store/ckin/front/address/adapter/AddressAdapter.java
- src/main/java/store/ckin/front/address/adapter/impl/AddressAdapterImpl.java
- src/main/java/store/ckin/front/address/controller/AddressController.java
- src/main/java/store/ckin/front/address/controller/SaleAddressController.java
- src/main/java/store/ckin/front/address/domain/AddressAttributeDto.java
- src/main/java/store/ckin/front/address/domain/request/AddressAddRequestDto.java
- src/main/java/store/ckin/front/address/domain/request/AddressUpdateRequestDto.java
- src/main/java/store/ckin/front/address/domain/response/MemberAddressResponseDto.java
- src/main/java/store/ckin/front/address/service/AddressService.java
- src/main/java/store/ckin/front/address/service/impl/AddressServiceImpl.java
- src/main/java/store/ckin/front/member/controller/MemberMyPageController.java
- src/main/java/store/ckin/front/member/service/MemberService.java
- src/main/java/store/ckin/front/sale/controller/SaleController.java
- src/main/resources/static/css/mypage-address.css
- src/main/resources/static/css/sale-address.css
- src/main/resources/static/js/address.js
- src/main/resources/templates/address/sale-main.html
- src/main/resources/templates/address/sale-update.html
- src/main/resources/templates/fragments/mypage/mypage-sidebar.html
- src/main/resources/templates/layouts/mypage-default.html
- src/main/resources/templates/member/mypage/address-main.html
- src/main/resources/templates/member/mypage/address-update.html
- src/main/resources/templates/sale/main.html
- 마이페이지에서 Address CRUD
- 주문 결제 페이지에서 Address CRUD
>
> [FEAT] Address 관련 View

- src/main/resources/static/css/main.css
- src/main/resources/static/css/main/navigation.css
- src/main/resources/templates/cart/index.html
#192 
상단 헤더의 크기 조절 및 정렬 관련 오류를 해결하였습니다
> [FIX] 헤더 크기 및 정렬 관련 오류 해결

- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/oauth/Oauth2SuccessHandler.java
> [DEPLOY FIX] Payco 로그인 오류 수정

- src/main/resources/application.properties
#201 
엘라스틱 서치 보안 요소 추가 (username, password) 등록
> [HOTFIX] elasticsearch username, password 설정

- src/main/java/store/ckin/front/address/adapter/impl/AddressAdapterImpl.java
- src/main/java/store/ckin/front/grade/adapter/GradeAdapter.java
- src/main/java/store/ckin/front/grade/adapter/impl/GradeAdapterImpl.java
- src/main/java/store/ckin/front/grade/controller/GradeController.java
- src/main/java/store/ckin/front/grade/domain/request/GradeCreateRequestDto.java
- src/main/java/store/ckin/front/grade/domain/request/GradeRequestDto.java
- src/main/java/store/ckin/front/grade/domain/request/GradeUpdateRequestDto.java
- src/main/java/store/ckin/front/grade/domain/response/GradeResponseDto.java
- src/main/java/store/ckin/front/grade/service/GradeService.java
- src/main/java/store/ckin/front/grade/service/impl/GradeServiceImpl.java
- src/main/java/store/ckin/front/member/controller/MemberController.java
- src/main/java/store/ckin/front/member/domain/request/MemberCreateRequestDto.java
- src/main/resources/static/js/grade.js
- src/main/resources/templates/admin/policy/grade/index.html
- src/main/resources/templates/fragments/admin-sidebar.html
> [FEAT] Grade

- src/main/java/store/ckin/front/advice/ErrorResponse.java
- src/main/java/store/ckin/front/advice/WebControllerAdvice.java
- src/main/resources/static/css/main.css
- src/main/resources/static/js/sale/form-check.js
- src/main/resources/static/js/search.js
- src/main/resources/templates/product/view.html
- src/main/resources/templates/sale/main.html
Front -> API 서버로 보낼 때 API 서버에서 내부적으로 에러가 발생한다면,
RestControllerAdvice에서 ErrorResponse 객체를 만들고, 해당 Exception에 알맞는 상태 코드와 함께 ErrorResponse로 응답하게 됩니다.
_말로 설명하기 어려워서 흐름을 그려봤습니다.. 알아보기 힘드시면 알려드리겠습니다! 🙇🏻‍♂️_
> 에러 메시지는 한글로 작성하는 것으로 진행하겠습니다 ! (API 서버에서 수정)
위의 사진에서 id, name과 같은 정보가 노출이 되어도 상관이 없을까요?
> [FEAT] Exception Handler

- src/main/resources/static/js/search.js
- src/main/resources/templates/product/view.html
_수량 3개가 추가된 모습_
_정상적으로 3개가 담긴 모습_
> [FEAT] 도서 상세 페이지 - 장바구니 & 즉시 구매 설정

- src/main/java/store/ckin/front/common/domain/PageInfo.java
- src/main/java/store/ckin/front/product/controller/ProductController.java
- src/main/java/store/ckin/front/product/repository/ProductSearchRepository.java
- src/main/java/store/ckin/front/product/service/ProductService.java
- src/main/java/store/ckin/front/product/service/impl/ProductServiceImpl.java
- src/main/resources/templates/product/search.html
> [FEAT] 검색 결과 Pageable 적용

- src/main/java/store/ckin/front/member/controller/MemberController.java
- src/main/java/store/ckin/front/member/controller/MemberMyPageController.java
- src/main/java/store/ckin/front/review/adapter/ReviewAdapter.java
- src/main/java/store/ckin/front/review/adapter/impl/ReviewAdapterImpl.java
- src/main/java/store/ckin/front/review/dto/request/UpdateReviewRequestDto.java
- src/main/java/store/ckin/front/review/service/ReviewService.java
- src/main/java/store/ckin/front/review/service/impl/ReviewServiceImpl.java
- src/main/resources/templates/member/mypage/review/main.html
> ex) [#183](https://github.com/nhnacademy-be4-ckin/ckin-front/issues/183)
> 리뷰 수정 기능 추가했습니다.
> [FEAT] 수정 모달 추가

- src/main/java/store/ckin/front/product/service/ProductService.java
> [DEPLOY] 6차 배포 - 수정

- src/main/java/store/ckin/front/util/JwtUtil.java
> [DEPLOY] 6차 배포 - 소나큐브 버그 수정 후 재배포

- src/main/java/store/ckin/front/product/service/impl/ProductServiceImpl.java
> [FIX] 레디스 널값을 인지하지 못하는 오류 수정

- src/main/resources/static/js/cart.js
> [FIX] 상품 수량 조작시 검증 안되던 버그 해결

- src/main/java/store/ckin/front/product/controller/ProductController.java
- src/main/java/store/ckin/front/product/controller/SearchController.java
- src/main/java/store/ckin/front/product/repository/ProductSearchRepository.java
- src/main/java/store/ckin/front/product/service/ProductService.java
- src/main/java/store/ckin/front/product/service/impl/ProductServiceImpl.java
- src/main/java/store/ckin/front/util/AlertUtil.java
- src/main/resources/static/js/search.js
- src/main/resources/templates/fragments/index-header.html
- src/main/resources/templates/product/search.html
#234 
검색 화면 좌측편에 필터링 관련 element를 배치하였습니다
```java
public PagedResponse<List<SearchProduct>> findProductByKeyword(String keyword, PageRequest pageRequest, List<String> filters, List<String> categories) {
BoolQueryBuilder query = QueryBuilders.boolQuery()
.must(QueryBuilders.multiMatchQuery(keyword)
.fields(getAdditionalFilter(filters))
);
for(String category: categories) {
query.must(addCategoryQuery(category));
}
```
기존 `MultimatchQuery`만 사용했던 코드에서 BoolQuery로 변경하여 다중 조건 및 옵션을 줄 수 있도록 변경하였습니다.
```java
private QueryBuilder addCategoryQuery(String category) {
return QueryBuilders.matchQuery("category", category);
}
private Map<String, Float> getAdditionalFilter(List<String> filters) {
Map<String, Float> result = new HashMap<>();
for(String filter: filters) {
if(filter.equals("title")) { …
```
> 검색 필터링 기능 추가(검색 대상)

- src/main/java/store/ckin/front/category/adapter/CategoryAdapter.java
- src/main/java/store/ckin/front/category/adapter/impl/CategoryAdapterImpl.java
- src/main/java/store/ckin/front/category/controller/CategoryRestController.java
- src/main/java/store/ckin/front/category/dto/response/CategoryCacheResponseDto.java
- src/main/java/store/ckin/front/category/service/CategoryService.java
- src/main/java/store/ckin/front/category/service/impl/CategoryServiceImpl.java
- src/main/java/store/ckin/front/config/RedisConfig.java
- src/main/java/store/ckin/front/config/properties/RedisProperties.java
- src/main/java/store/ckin/front/product/service/impl/ProductServiceImpl.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
- src/main/resources/static/js/nav-script.js
- src/main/resources/templates/admin/book/create.html
- src/main/resources/templates/admin/book/update.html
> redis 서버 카테고리 캐싱 구현 및 기타 오류 수정
> [FEATURE] 카테고리 캐싱

- src/main/resources/static/js/sale/coupon.js
> [DEPLOY] 최종 배포

- src/main/resources/static/css/main.css
- src/main/resources/static/js/search.js
- src/main/resources/templates/product/search.html
> 검색 필터 (카테고리) 적용 및 리팩토링

- src/main/resources/static/js/sale/coupon.js
- src/main/resources/templates/api-docs.html
- src/main/resources/templates/coupon-docs.html
- src/main/resources/templates/sale/guest-order-detail.html
> [DEPLOY] 최종 배포-1

- src/main/resources/static/css/main.css
- src/main/resources/templates/product/search.html
> [FEAT] 검색 결과에서 저자, 출판사 대상 새로운 검색 기능 추가

- src/main/resources/templates/admin/policy/grade/index.html
> [FIX] 관리자 페이지 등급 조건 형식 변경

- src/main/java/store/ckin/front/config/PasswordEncoderConfig.java
- src/main/java/store/ckin/front/config/SecurityConfig.java
- src/main/java/store/ckin/front/member/adapter/MemberAdapter.java
- src/main/java/store/ckin/front/member/adapter/impl/MemberAdapterImpl.java
- src/main/java/store/ckin/front/member/filter/JwtFilter.java
- src/main/java/store/ckin/front/member/service/MemberService.java
- src/main/java/store/ckin/front/member/service/impl/MemberServiceImpl.java
> [FEAT] 서비스 이용 시 최근 로그인 기록 업데이트

- front.iml
- src/main/resources/templates/index.html
신간도서 및 인기도서 옆에 있는 `자세히 보기 > `에 대해 링크가 걸려있지 않아 수정하였습니다.
> [FEAT] 자세히 보기 링크 추가
